spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liu520yan/config-repostory/
#          uri: http://git.oschina.net/didispace/config-repo-demo/
server:
  port: 1201