server:
  port: 8888
zuul:
  routes:
    resources:
      path: /resources/**
      url: http://localhost:9090/

      #忽略的敏感信息
      sensitive-headers:
      custom-sensitive-headers: true
spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/