server:
  port: 8888
zuul:
  routes:
    resources:
      path: localhost://**
      url: /**
      #忽略的敏感信息
      sensitive-headers:
      custom-sensitive-headers: true
spring:
  application:
    name: gateway
  redis:
    host: 39.108.223.226
    port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.xuey.top/eureka/

login:
  userName: liuyan
  password: liuyan