server:
  port: 9999
debug: false
#jwt 过期时间 单位： 秒
accessTokenValiditySeconds: 6000
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/
spring:
  application:
    name: oauth2